# Generated by Django 3.2.20 on 2023-08-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=' ', upload_to='advertisements/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
